---
- hosts: prometheus
  become: true
  roles:
    - prometheus
  # tags:
  # - prometheus
  vars:
    prometheus_targets:
      node:
        - targets:
            - nginx1.private.donets:9100
            - nginx2.private.donets:9100
            - nginx1.private.donets:4040
            - nginx2.private.donets:4040

- hosts: grafana
  become: true
  become_user: root
  tasks:
    - name: Download grafana deb
      apt:
        deb: "https://dl.grafana.com/oss/release/grafana_11.0.0_amd64.deb"
  tags:
    - grafana
  # Запуск роли

- hosts: grafana
  become: true
  roles:
    - grafana
  tags:
    - grafana

- hosts: elc
  become: true
  become_user: root
  tasks:
    - name: Download elc deb
      apt:
        deb: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.17.14-amd64.deb
  tags:
    - elc

- hosts: elc
  become: true
  become_user: root
  roles:
    - elc
  tags:
    - elc

- hosts: kibana
  become: true
  become_user: root
  tasks:
    - name: Download kibana deb
      apt:
        deb: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.17.14-amd64.deb
  tags:
    - kibana

- hosts: kibana
  become: true
  become_user: root
  roles:
    - kibana
  tags:
    - kibana

- hosts: nginx
  become: true
  roles:
    - nginx
  tags:
    - nginx

- hosts: nginx
  become: true
  tasks:
    - name: Install a .deb package
      apt:
        deb: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-8.10.3-amd64.deb
  tags:
    - nginx

- hosts: nginx
  become: true
  roles:
    - filebeat
    - node_exporter
    - prometheus-nginxlog-exporter
  tags:
    - nginx

- hosts: nginx
  become: true
  tasks:
    - name: Filebeat setup
      script: ./shell.sh
  tags:
    - nginx2
