cluster.name: elc #<--меняем имя кластера
node.name: elc-1 #<--меняем название ноды, если нужно
node.roles: [ master, data, ingest ] #<--какую функцию будет выполнять эта нода
cluster.initial_master_nodes: ["elc-1"] #<--узлы, участвующие в голосовании по
#выбору мастера
#discovery.seed_hosts: ["ip-адрес"] # <--список возможных мастеров кластера
path.data: /var/lib/elasticsearch #<-где храним данные
path.logs: /var/log/elasticsearch # <--куда пишем логи
network.host: 0.0.0.0
# xpack.security.transport.ssl.enabled: true
# xpack.security.http.ssl:
#   enabled: true
#   keystore.path: certs/http.p12
# xpack.security.transport.ssl:
#   enabled: true
#   verification_mode: certificate
#   keystore.path: certs/transport.p12
#   truststore.path: certs/transport.p12