---
dependencies: []

galaxy_info:
  role_name: kibana
  author: geerlingguy
  description: Kibana for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.10
  platforms:
    - name: Debian
      versions:
        - jessie
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
  galaxy_tags:
    - web
    - system
    - monitoring
    - kibana
    - elk
    - efk
    - logging
    - dataviz
