---
# tasks file for nginx
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install nginx
  apt:
    name: nginx
    state: present
  become: true
  become_method: sudo

- name: Copy config file with owner and permissions
  become: true
  template:
    src: /home/netology/vagrantproject/terproject/roles/nginx/templates/index.j2
    dest: /var/www/html/index.html
    mode: "0555"
  notify: Restart nginx

- service:
    name: nginx
    state: started
  become: true
  become_method: sudo

# - name: generate index.html
#   template: ps aux
#     src: "index.j2"
#     dest: "{{ destin_file }}/index.html"
#     mode: '0555'

- name: Enable service nginx
  ansible.builtin.systemd_service:
    name: nginx.service
    enabled: true
